services:
  - type: web
    name: rule-engine-service
    env: docker
    branch: master
    dockerfilePath: rule-engine-service/Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8083"

  - type: web
    name: quote-service
    env: docker
    branch: master
    dockerfilePath: quote-service/Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8082"
      - key: RULE_ENGINE_URL
        value: "https://rule-engine-service.onrender.com"
